use crate::memory::MemoryError;

pub(crate) struct Header {
    pub title: String,
    pub manufacturer_code: String,
    pub cgb_flag: u8,
    pub new_licensee_code: String,
    pub sgb_flag: u8,
    pub cart_type: u8,
    pub rom_size_code: u8,
    pub ram_size_code: u8,
    pub destination_code: u8,
    pub old_licensee_code: u8,
    pub mask_rom_version_number: u8,
    pub header_checksum: u8,
    pub global_checksum: [u8; 2],

    pub licensee: String,
    pub rom_size: usize,
    pub ram_size: usize,
    pub rom_banks: usize,
    pub ram_banks: usize,
}

impl Header {
    pub fn parse(data: &[u8; 0x50]) -> Result<Self, MemoryError> {
        let title = String::from_utf8_lossy(&data[0x34..=0x43])
            .trim_end_matches('\0')
            .to_string();
        let manufacturer_code = String::from_utf8_lossy(&data[0x3F..=0x42])
            .trim_end_matches('\0')
            .to_string();
        let new_licensee_code = String::from_utf8_lossy(&data[0x44..=0x45])
            .trim_end_matches('\0')
            .to_string();
        let licensee = if data[0x1C] == 0x33 {
            Self::licensee_from_new_code(&new_licensee_code).unwrap_or("Unknown")
        } else {
            Self::licensee_from_old_code(data[0x1C]).unwrap_or("Unknown")
        }
        .to_string();
        let (rom_size, rom_banks) = Self::rom_size_and_banks(data[0x19])?;
        let (ram_size, ram_banks) = Self::ram_size_and_banks(data[0x1A])?;

        Ok(Self {
            title,
            manufacturer_code,
            cgb_flag: data[0x16],
            new_licensee_code,
            sgb_flag: data[0x17],
            cart_type: data[0x18],
            rom_size_code: data[0x19],
            ram_size_code: data[0x1A],
            destination_code: data[0x1B],
            old_licensee_code: data[0x1C],
            mask_rom_version_number: data[0x1D],
            header_checksum: data[0x1E],
            global_checksum: [data[0x1F], data[0x20]],
            licensee,
            rom_size,
            ram_size,
            rom_banks,
            ram_banks,
        })
    }

    fn rom_size_and_banks(code: u8) -> Result<(usize, usize), MemoryError> {
        let banks = match code {
            0x00 => 2,
            0x01 => 4,
            0x02 => 8,
            0x03 => 16,
            0x04 => 32,
            0x05 => 64,
            0x06 => 128,
            0x07 => 256,
            0x08 => 512,
            0x52 => 72,
            0x53 => 80,
            0x54 => 96,
            _ => return Err(format!("Unsupported ROM size code: 0x{code:02X}")),
        };

        Ok((banks * 0x4000, banks))
    }

    fn ram_size_and_banks(code: u8) -> Result<(usize, usize), MemoryError> {
        let banks = match code {
            0x00 => 0,
            0x01 => 0,
            0x02 => 1,
            0x03 => 4,
            0x04 => 16,
            0x05 => 8,
            _ => return Err(format!("Unsupported RAM size code: 0x{code:02X}")),
        };

        Ok((banks * 0x2000, banks))
    }

    fn licensee_from_old_code(code: u8) -> Result<&'static str, MemoryError> {
        Ok(match code {
            0x00 => "None",
            0x01 => "Nintendo",
            0x08 => "Capcom",
            0x09 => "HOT-B",
            0x0A => "Jaleco",
            0x0B => "Coconuts Japan",
            0x0C => "Elite Systems",
            0x13 => "EA (Electronic Arts)",
            0x18 => "Hudson Soft",
            0x19 => "ITC Entertainment",
            0x1A => "Yanoman",
            0x1D => "Japan Clary",
            0x1F => "Virgin Games Ltd.",
            0x24 => "PCM Complete",
            0x25 => "San-X",
            0x28 => "Kemco",
            0x29 => "SETA Corporation",
            0x30 => "Infogrames",
            0x31 => "Nintendo",
            0x32 => "Bandai",
            0x33 => {
                return Err(format!(
                    "Licensee code 0x33 indicates that the new licensee code should be used instead"
                ));
            }
            0x34 => "Konami",
            0x35 => "HectorSoft",
            0x38 => "Capcom",
            0x39 => "Banpresto",
            0x3C => "Entertainment Interactive",
            0x3E => "Gremlin",
            0x41 => "Ubi Soft",
            0x42 => "Atlus",
            0x44 => "Malibu Interactive",
            0x46 => "Angel",
            0x47 => "Spectrum HoloByte",
            0x49 => "Irem",
            0x4A => "Virgin Games Ltd.",
            0x4D => "Malibu Interactive",
            0x4F => "U.S. Gold",
            0x50 => "Absolute",
            0x51 => "Acclaim Entertainment",
            0x52 => "Activision",
            0x53 => "Sammy USA Corporation",
            0x54 => "GameTek",
            0x55 => "Park Place",
            0x56 => "LJN",
            0x57 => "Matchbox",
            0x59 => "Milton Bradley Company",
            0x5A => "Mindscape",
            0x5B => "Romstar",
            0x5C => "Naxat Soft",
            0x5D => "Tradewest",
            0x60 => "Titus Interactive",
            0x61 => "Virgin Games Ltd.",
            0x67 => "Ocean Software",
            0x69 => "EA (Electronic Arts)",
            0x6E => "Elite Systems",
            0x6F => "Electro Brain",
            0x70 => "Infogrames",
            0x71 => "Interplay Entertainment",
            0x72 => "Broderbund",
            0x73 => "Sculptured Software",
            0x75 => "The Sales Curve Limited",
            0x78 => "THQ",
            0x79 => "Accolade",
            0x7A => "Triffix Entertainment",
            0x7C => "MicroProse",
            0x7F => "Kemco",
            0x80 => "Misawa Entertainment",
            0x83 => "LOZC G.",
            0x86 => "Tokuma Shoten",
            0x8B => "Bullet-Proof Software",
            0x8C => "Vic Tokai Corp.",
            0x8E => "Ape Inc.",
            0x8F => "I'Max",
            0x91 => "Chunsoft Co.",
            0x92 => "Video System",
            0x93 => "Tsubaraya Productions",
            0x95 => "Varie",
            0x96 => "Yonezawa / S'Pal",
            0x97 => "Kemco",
            0x99 => "Arc",
            0x9A => "Nihon Bussan",
            0x9B => "Tecmo",
            0x9C => "Imagineer",
            0x9D => "Banpresto",
            0x9F => "Nova",
            0xA1 => "Hori Electric",
            0xA2 => "Bandai",
            0xA4 => "Konami",
            0xA6 => "Kawada",
            0xA7 => "Takara",
            0xA9 => "Technos Japan",
            0xAA => "Broderbund",
            0xAC => "Toei Animation",
            0xAD => "Toho",
            0xAF => "Namco",
            0xB0 => "Acclaim Entertainment",
            0xB1 => "ASCII Corporation or Nexsoft",
            0xB2 => "Bandai",
            0xB4 => "Square Enix",
            0xB6 => "HAL Laboratory",
            0xB7 => "SNK",
            0xB9 => "Pony Canyon",
            0xBA => "Culture Brain",
            0xBB => "Sunsoft",
            0xBD => "Sony Imagesoft",
            0xBF => "Sammy Corporation",
            0xC0 => "Taito",
            0xC2 => "Kemco",
            0xC3 => "Square",
            0xC4 => "Tokuma Shoten",
            0xC5 => "Data East",
            0xC6 => "Tonkin House",
            0xC8 => "Koei",
            0xC9 => "UFL",
            0xCA => "Ultra Games",
            0xCB => "VAP, Inc.",
            0xCC => "Use Corporation",
            0xCD => "Meldac",
            0xCE => "Pony Canyon",
            0xCF => "Angel",
            0xD0 => "Taito",
            0xD1 => "SOFEL (Software Engineering Lab)",
            0xD2 => "Quest",
            0xD3 => "Sigma Enterprises",
            0xD4 => "ASK Kodansha Co.",
            0xD6 => "Naxat Soft",
            0xD7 => "Copya System",
            0xD9 => "Banpresto",
            0xDA => "Tomy",
            0xDB => "LJN",
            0xDD => "Nippon Computer Systems",
            0xDE => "Human Ent.",
            0xDF => "Altron",
            0xE0 => "Jaleco",
            0xE1 => "Towa Chiki",
            0xE2 => "Yutaka",
            0xE3 => "Varie",
            0xE5 => "Epoch",
            0xE7 => "Athena",
            0xE8 => "Asmik Ace Entertainment",
            0xE9 => "Natsume",
            0xEA => "King Records",
            0xEB => "Atlus",
            0xEC => "Epic / Sony Records",
            0xEE => "IGS",
            0xF0 => "A Wave",
            0xF3 => "Extreme Entertainment",
            0xFF => "LJN",
            _ => return Err(format!("Unknown old licensee code: 0x{code:02X}")),
        })
    }

    fn licensee_from_new_code(code: &str) -> Result<&'static str, MemoryError> {
        Ok(match code {
            "00" => "None",
            "01" => "Nintendo Research & Development 1",
            "08" => "Capcom",
            "13" => "EA (Electronic Arts)",
            "18" => "Hudson Soft",
            "19" => "B-AI",
            "20" => "KSS",
            "22" => "Planning Office WADA",
            "24" => "PCM Complete",
            "25" => "San-X",
            "28" => "Kemco",
            "29" => "SETA Corporation",
            "30" => "Viacom",
            "31" => "Nintendo",
            "32" => "Bandai",
            "33" => "Ocean Software / Acclaim Entertainment",
            "34" => "Konami",
            "35" => "HectorSoft",
            "37" => "Taito",
            "38" => "Hudson Soft",
            "39" => "Banpresto",
            "41" => "Ubi Soft",
            "42" => "Atlus",
            "44" => "Malibu Interactive",
            "46" => "Angel",
            "47" => "Bullet-Proof Software",
            "49" => "Irem",
            "50" => "Absolute",
            "51" => "Acclaim Entertainment",
            "52" => "Activision",
            "53" => "Sammy USA Corporation",
            "54" => "Konami",
            "55" => "Hi Tech Expressions",
            "56" => "LJN",
            "57" => "Matchbox",
            "58" => "Mattel",
            "59" => "Milton Bradley Company",
            "60" => "Titus Interactive",
            "61" => "Virgin Games Ltd.",
            "64" => "Lucasfilm Games",
            "67" => "Ocean Software",
            "69" => "EA (Electronic Arts)",
            "70" => "Infogrames",
            "71" => "Interplay Entertainment",
            "72" => "Broderbund",
            "73" => "Sculptured Software",
            "75" => "The Sales Curve Limited",
            "78" => "THQ",
            "79" => "Accolade",
            "80" => "Misawa Entertainment",
            "83" => "LOZC G.",
            "86" => "Tokuma Shoten",
            "87" => "Tsukuda Original",
            "91" => "Chunsoft Co.",
            "92" => "Video System",
            "93" => "Ocean Software / Acclaim Entertainment",
            "95" => "Varie",
            "96" => "Yonezawa / S'Pal",
            "97" => "Kaneko",
            "99" => "Pack-In-Video",
            "9H" => "Bottom Up",
            "A4" => "Konami (Yu-Gi-Oh!)",
            "BL" => "MTO",
            "DK" => "Kodansha",
            "D0" => "Taito",
            "D1" => "SOFEL (Software Engineering Lab)",
            "D2" => "Quest",
            "D3" => "Sigma Enterprises",
            "D4" => "ASK Kodansha Co.",
            "D6" => "Naxat Soft",
            "D7" => "Copya System",
            "D9" => "Banpresto",
            "DA" => "Tomy",
            "DB" => "LJN",
            "DD" => "Nippon Computer Systems",
            "DE" => "Human Ent.",
            "DF" => "Altron",
            "E0" => "Jaleco",
            "E1" => "Towa Chiki",
            "E2" => "Yutaka",
            "E3" => "Varie",
            "E5" => "Epoch",
            "E7" => "Athena",
            "E8" => "Asmik Ace Entertainment",
            "E9" => "Natsume",
            "EA" => "King Records",
            "EB" => "Atlus",
            "EC" => "Epic / Sony Records",
            "EE" => "IGS",
            "F0" => "A Wave",
            "F3" => "Extreme Entertainment",
            "FF" => "LJN",
            _ => return Err(format!("Unknown new licensee code: {code}")),
        })
    }
}
